version: '3'

services:
  database:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: provaAF
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
    image: meu-projeto-springboot:latest
    container_name: api-service
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_NAME: provaAF
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"

volumes:
  db-volume:
